### ISSUE TITLE
Integrate DNN Security Roles with YAF User Roles

### ISSUE THREAD

**Issue by JaySMa** [YAFNET/YAFNET-DNN#38]
See if there's a way to integrate the DNN security roles of a user with those of the YAF user roles.

For example, registered a new user and within YAF, set them to be a forum advisor.  But, still had to go into the DNN user settings and assign them to the forum advisor DNN security role so they get the proper access as well.

Thanks..

**Comment by w8tcha** [comment]
I understand the scenario but allowing assigning roles inside yaf would cause more problems. The synchronize function would automatically remove the user from the role.

If you want to give a user certain permission to an access mask via the roles. you can assign a user directly to an access mask instead of a user role

**Comment by JaySMa** [comment]
OK, no problem and I understand.

Thank you..
